#!/usr/bin/env python3
"""
label_ground_truth.py -- interactive hand-labeling for a recorded session's
extracted frames (sessions/<name>/frames/, from unpack_session.py).

Two independent ground truths, same precedent as session_101's
blink_labels.csv (see memory: hand labels checked against the classifier,
NOT generated by it):

  --mode eye    click the true eye center on a sampled frame every --step
                frames. Writes frame_idx,timestamp_ms,eye_x,eye_y (pixel
                coords in the raw 320x240 frame). Optionally overlays the
                pipeline's own predicted ROI (--pred-csv, a roi_x,roi_y
                CSV like drift_result.csv) in a second color so you can see
                agreement live -- but the click is what gets saved, not a
                snap-to-box.

  --mode blink  step one frame at a time through a window and press a key
                for eye state: o=open c=closed s=squint/partial u=unsure.
                Writes frame_idx,timestamp_ms,state (same schema as
                sessions/session_101/blink_labels.csv).

Both modes resume: existing rows in --out are loaded first and those frame
indices are skipped.

Usage:
    python label_ground_truth.py --session ../../sessions/session_116 \\
        --mode eye --step 20 --out ../../sessions/session_116/eye_gt.csv \\
        --pred-csv /path/to/drift_result.csv

    python label_ground_truth.py --session ../../sessions/session_116 \\
        --mode blink --start-ms 240000 --end-ms 270000 \\
        --out ../../sessions/session_116/blink_labels.csv

Keys (both modes): SPACE/o/c/s/u = label+advance (see above), b = back,
q = quit and save, z = undo last saved row.
"""

import argparse
import csv
import os
import sys

import cv2

DISPLAY_SCALE = 3  # 320x240 native frame is small; upscale for clicking/reading


def load_frames(session_dir):
    frames_dir = os.path.join(session_dir, "frames")
    if not os.path.isdir(frames_dir):
        sys.exit(f"[ERROR] no frames/ in {session_dir} -- run unpack_session.py first")
    names = [f for f in os.listdir(frames_dir) if f.endswith(".jpg")]
    entries = sorted((int(os.path.splitext(f)[0]), f) for f in names)
    return frames_dir, entries  # entries[i] = (timestamp_ms, filename), index i = frame_idx


def load_pred(pred_csv):
    """timestamp_ms -> (roi_x, roi_y) from a drift_result.csv-shaped file, or None."""
    if not pred_csv:
        return {}
    pred = {}
    with open(pred_csv, newline="") as f:
        for row in csv.DictReader(f):
            try:
                pred[int(row["timestamp_ms"])] = (int(row["roi_x"]), int(row["roi_y"]))
            except (KeyError, ValueError):
                continue
    return pred


def load_existing(out_path, key_field):
    done = set()
    rows = []
    if os.path.exists(out_path):
        with open(out_path, newline="") as f:
            for row in csv.DictReader(f):
                rows.append(row)
                done.add(int(row[key_field]))
    return rows, done


def save(out_path, fieldnames, rows):
    with open(out_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def mode_eye(frames_dir, entries, args):
    fieldnames = ["frame_idx", "timestamp_ms", "eye_x", "eye_y"]
    rows, done = load_existing(args.out, "frame_idx")
    pred = load_pred(args.pred_csv)

    indices = list(range(0, len(entries), args.step))
    if args.start_frame:
        indices = [i for i in indices if i >= args.start_frame]
    if args.end_frame:
        indices = [i for i in indices if i <= args.end_frame]
    indices = [i for i in indices if i not in done]
    if not indices:
        print("[OK] nothing left to label (all sampled frames already in", args.out, ")")
        return

    click = {}

    def on_mouse(event, x, y, flags, userdata):
        if event == cv2.EVENT_LBUTTONDOWN:
            click["xy"] = (x // DISPLAY_SCALE, y // DISPLAY_SCALE)

    win = "label eye (click eye center, SPACE=confirm, b=back, q=quit)"
    cv2.namedWindow(win)
    cv2.setMouseCallback(win, on_mouse)

    i = 0
    while 0 <= i < len(indices):
        frame_idx = indices[i]
        ts, fname = entries[frame_idx]
        img = cv2.imread(os.path.join(frames_dir, fname))
        if img is None:
            i += 1
            continue
        disp = cv2.resize(img, None, fx=DISPLAY_SCALE, fy=DISPLAY_SCALE, interpolation=cv2.INTER_NEAREST)

        if ts in pred:
            px, py = pred[ts]
            cv2.circle(disp, (px * DISPLAY_SCALE, py * DISPLAY_SCALE), 6, (0, 165, 255), 1)

        if "xy" in click:
            cx, cy = click["xy"]
            cv2.drawMarker(disp, (cx * DISPLAY_SCALE, cy * DISPLAY_SCALE), (0, 255, 0),
                            cv2.MARKER_CROSS, 16, 2)

        label = f"frame {frame_idx}  t={ts/1000:.1f}s  ({i+1}/{len(indices)})  labeled={len(rows)}"
        cv2.putText(disp, label, (8, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
        cv2.putText(disp, label, (8, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 1)
        cv2.imshow(win, disp)

        k = cv2.waitKey(30) & 0xFF
        if k == ord("q"):
            break
        elif k == ord("b"):
            click.pop("xy", None)
            i = max(0, i - 1)
        elif k in (ord(" "), 13) and "xy" in click:
            cx, cy = click["xy"]
            rows.append({"frame_idx": frame_idx, "timestamp_ms": ts, "eye_x": cx, "eye_y": cy})
            save(args.out, fieldnames, rows)
            click.pop("xy", None)
            i += 1
        elif k == ord("z") and rows:
            rows.pop()
            save(args.out, fieldnames, rows)

    cv2.destroyAllWindows()
    print(f"[OK] {len(rows)} eye-location labels in {args.out}")


def mode_blink(frames_dir, entries, args):
    fieldnames = ["timestamp_ms", "frame_idx", "state"]
    rows, done = load_existing(args.out, "frame_idx")

    indices = list(range(len(entries)))
    if args.start_ms is not None:
        indices = [i for i in indices if entries[i][0] >= args.start_ms]
    if args.end_ms is not None:
        indices = [i for i in indices if entries[i][0] <= args.end_ms]
    if args.start_frame:
        indices = [i for i in indices if i >= args.start_frame]
    if args.end_frame:
        indices = [i for i in indices if i <= args.end_frame]
    indices = [i for i in indices if i not in done]
    if not indices:
        print("[OK] nothing left to label in that window (already in", args.out, ")")
        return

    key_state = {ord("o"): "open", ord("c"): "closed", ord("s"): "squint", ord("u"): "unsure"}
    win = "label blink (o=open c=closed s=squint u=unsure, b=back, q=quit)"
    cv2.namedWindow(win)

    i = 0
    while 0 <= i < len(indices):
        frame_idx = indices[i]
        ts, fname = entries[frame_idx]
        img = cv2.imread(os.path.join(frames_dir, fname))
        if img is None:
            i += 1
            continue

        # Crop to the ROI if we know one (much easier to judge open/closed
        # zoomed in than squinting at a 320x240 frame), else show full frame.
        if args.roi:
            rx, ry, rs = args.roi
            m = rs  # a bit of margin around the stored ROI
            x0, y0 = max(0, rx - m // 2), max(0, ry - m // 2)
            crop = img[y0:y0 + rs + m, x0:x0 + rs + m]
            if crop.size:
                img = crop

        disp = cv2.resize(img, None, fx=6, fy=6, interpolation=cv2.INTER_NEAREST)
        label = f"frame {frame_idx}  t={ts/1000:.1f}s  ({i+1}/{len(indices)})  labeled={len(rows)}"
        cv2.putText(disp, label, (8, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
        cv2.putText(disp, label, (8, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
        cv2.imshow(win, disp)

        k = cv2.waitKey(0) & 0xFF
        if k == ord("q"):
            break
        elif k == ord("b"):
            i = max(0, i - 1)
        elif k == ord("z") and rows:
            rows.pop()
            save(args.out, fieldnames, rows)
        elif k in key_state:
            rows.append({"timestamp_ms": ts, "frame_idx": frame_idx, "state": key_state[k]})
            save(args.out, fieldnames, rows)
            i += 1

    cv2.destroyAllWindows()
    print(f"[OK] {len(rows)} blink-state labels in {args.out}")


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--session", required=True)
    p.add_argument("--mode", required=True, choices=["eye", "blink"])
    p.add_argument("--out", required=True)
    p.add_argument("--step", type=int, default=20, help="[eye mode] sample every N frames (default 20)")
    p.add_argument("--pred-csv", default=None, help="[eye mode] drift_result.csv-shaped file to overlay")
    p.add_argument("--roi", default=None, help="[blink mode] x,y,size to crop to, e.g. 195,124,48")
    p.add_argument("--start-frame", type=int, default=None)
    p.add_argument("--end-frame", type=int, default=None)
    p.add_argument("--start-ms", type=int, default=None, help="[blink mode]")
    p.add_argument("--end-ms", type=int, default=None, help="[blink mode]")
    args = p.parse_args()
    if args.roi:
        args.roi = tuple(int(v) for v in args.roi.split(","))
    return args


def main():
    args = parse_args()
    frames_dir, entries = load_frames(args.session)
    print(f"[INFO] {len(entries)} frames in {frames_dir}")
    if args.mode == "eye":
        mode_eye(frames_dir, entries, args)
    else:
        mode_blink(frames_dir, entries, args)


if __name__ == "__main__":
    main()
