#!/usr/bin/env python3
"""Blink classifier with a running open-eye template subtracted (session-to-session appearance drops out).

score_t = f_t . w1 + (f_t - B_{t-1}) . w2 + bias,   B_t = (1-a) B_{t-1} + a f_t,   B_0 = f_0   (causal: the device can do this)

f is the 756-value HOG vector. B is a running average of recent frames' features, i.e. roughly this rider's
open-eye look right now (a blink is ~5% of frames, so it barely moves B). Because the model is linear,
  score_t = f_t . (w1+w2) - s_{t-1} + bias,   s_t = (1-a) s_{t-1} + a (f_t . w2)
so the device needs two dot products per frame and ONE float of state -- no 756-float buffer.

Leave-one-session-out on fixed-ROI (device-like) crops, class weight 1, C 0.1, alpha 0.05:
mean F1 0.69 vs 0.64 without the template (119: 0.52 vs 0.41).

Usage: python train_blink_bgsub.py --sessions sessions/session_119 sessions/session_121 sessions/session_122 \
           --header ../firmware/src/BlinkWeights.pooled_bgsub.h --model sessions/session_122/bgsub_model.bin
"""
import argparse
import numpy as np
import train_blink_classifier as T
import train_blink_devicelike as DLK

HOG = T.HOG_LEN


def ema_sub(X, a):
    """X - B, B[i] = running average of X[:i] (B[0] = X[0]); identical to the device's scalar recurrence."""
    out = np.empty_like(X); b = X[0].astype(np.float64)
    for i in range(len(X)):
        out[i] = X[i] - b; b = (1 - a) * b + a * X[i]
    return out


def feats(X, a): return np.hstack([X, ema_sub(X, a)])


def write_header(path, wa, wb, bias, th, alpha, provenance):
    def f(v):
        s = "%.9g" % np.float32(v)
        return (s + ".0" if not any(c in s for c in ".eE") else s) + "f"
    def arr(name, w):
        return f"static const float {name}[] = {{\n" + ",\n".join("    " + ", ".join(f(v) for v in w[i:i + 6]) for i in range(0, len(w), 6)) + "\n};\n"
    with open(path, "w", newline="\n") as o:
        o.write("// Generated by fatigue-helmet/python/train_blink_bgsub.py -- do not edit by hand.\n"
                + "".join("// " + l + "\n" for l in provenance)
                + "// score = f.WEIGHTS - s + BIAS; s tracks f.WEIGHTS_BG with rate BG_ALPHA (see HogBackground in EyeBlinkEAR.h).\n"
                "// Rider- and mount-specific: retrain for a different rider or camera position.\n"
                "#pragma once\n#include \"EyeBlinkEAR.h\"\n\n"
                "#define BLINK_HOG_BGSUB 1   // main.cpp / session_replay use the two-vector, running-template scoring\n"
                f"static const float BLINK_HOG_BIAS      = {f(bias)};\n"
                f"static const float BLINK_HOG_THRESHOLD = {f(th)};\n"
                f"static const float BLINK_HOG_BG_ALPHA  = {f(alpha)};\n"
                "static const int   BLINK_HOG_BG_WARMUP_FRAMES = 15;   // no detections until the template has settled\n"
                + arr("BLINK_HOG_WEIGHTS", wa) + arr("BLINK_HOG_WEIGHTS_BG", wb)
                + "static_assert(sizeof(BLINK_HOG_WEIGHTS) / sizeof(BLINK_HOG_WEIGHTS[0]) == EyeBlinkEAR::HOG_LEN, \"weights do not match the firmware's HOG feature length\");\n"
                "static_assert(sizeof(BLINK_HOG_WEIGHTS_BG) / sizeof(BLINK_HOG_WEIGHTS_BG[0]) == EyeBlinkEAR::HOG_LEN, \"bg weights do not match the HOG length\");\n")


def write_model(path, wa, wb, bias, th, alpha):
    """Replay-tool model file: wa[756], wb[756], bias, threshold, alpha (float32)."""
    np.concatenate([wa, wb, [bias, th, alpha]]).astype("<f4").tofile(path)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sessions", nargs="+", required=True); ap.add_argument("--header", required=True)
    ap.add_argument("--model", help="also write the replay-tool model file here")
    ap.add_argument("--alpha", type=float, default=0.05); ap.add_argument("--threshold", type=float, default=-0.25)
    ap.add_argument("--no-loso", action="store_true")
    a = ap.parse_args()
    Ds = [DLK.load(s) for s in a.sessions]
    ths = np.round(np.arange(-1.0, 1.51, 0.25), 2)
    F = [dict(Xa=feats(D["Xa"], a.alpha), Xd=feats(D["Xd"], a.alpha)) for D in Ds]
    def stack(idx):
        X = [f[k][Ds[i]["usable"]] for i in idx for f in [F[i]] for k in ("Xa", "Xd")]
        y = [Ds[i]["y"][Ds[i]["usable"]] for i in idx for _ in (0, 1)]
        return np.vstack(X), np.concatenate(y)
    loso = "not measured (--no-loso)"
    if not a.no_loso:
        cur = []
        for i, te in enumerate(Ds):
            w, b = DLK.train(*stack([j for j in range(len(Ds)) if j != i]), 1)
            sc = F[i]["Xd"] @ w + b; cur.append({float(t): DLK.score(te, sc, t) for t in ths})
        for t in (a.threshold - 0.25, a.threshold, a.threshold + 0.25):
            print(f"leave-one-session-out at threshold {t:+.2f}: F1 {[round(c[float(t)][0], 2) for c in cur]} mean {np.mean([c[float(t)][0] for c in cur]):.3f}; "
                  f"detected/true rate {[round(c[float(t)][1] / c[float(t)][2], 1) for c in cur]}", flush=True)
        loso = f"mean F1 {np.mean([c[float(a.threshold)][0] for c in cur]):.3f} at threshold {a.threshold:+.2f}"
    w, b = DLK.train(*stack(range(len(Ds))), 1)
    w1, w2 = w[:HOG], w[HOG:]; wa = (w1 + w2).astype(np.float32); wb = w2.astype(np.float32)
    write_header(a.header, wa, wb, float(b), a.threshold, a.alpha,
                 [f"Pooled {', '.join(s.rstrip('/').split('/')[-1] for s in a.sessions)}: [frame, frame - running template], alpha {a.alpha}, class weight 1.",
                  f"Leave-one-session-out on fixed-ROI crops: {loso}."])
    if a.model: write_model(a.model, wa, wb, float(b), a.threshold, a.alpha)
    print(f"final model -> {a.header}" + (f", {a.model}" if a.model else ""))


if __name__ == "__main__":
    main()
