#!/usr/bin/env python3
"""
train_blink_classifier.py — Train the firmware's HOG blink classifier from hand labels.
=======================================================================================
The firmware's HogBlinkDetector (src/EyeBlinkEAR.h) scores each frame as
weights . hog(crop) + bias and counts a blink when the score crosses a
threshold. This script finds those weights.

Everything that touches pixels runs through tools/session_replay, which
compiles the same EyeBlinkEAR.h the ESP32 does:
  1. session_replay --hog-dump   -> HOG features exactly as the device computes them
  2. train a linear SVM on those features against blink_labels.csv
  3. cross-validate END TO END: for each of 5 contiguous time blocks, train on
     the other blocks, write a model, and let session_replay (i.e. the
     firmware's scoring + blink-counting logic) find blinks in the held-out block
  4. train on everything and write <session>/blink_model.bin for session_replay
     and the same numbers as firmware/src/BlinkWeights.h for main.cpp

blink_labels.csv: timestamp_ms,frame_idx,state with state in
open / closed / squint / unsure. "unsure" frames (exposure dropouts, hand over
the camera, half-closures) are left out of training and of the scores.

Usage:
    python train_blink_classifier.py --session ../../sessions/session_101
"""

import argparse
import csv
import os
import subprocess
import sys

import cv2
import numpy as np

HOG_LEN = 756
HERE = os.path.dirname(os.path.abspath(__file__))
REPLAY = os.path.join(HERE, "..", "firmware", "tools", "session_replay", "session_replay.exe")
TOL = 2          # an event within 2 frames of a labelled closed frame is that blink
FOLDS = 5


def replay(session, out_dir, *flags):
    cmd = [REPLAY, os.path.join(session, "frames"), os.path.join(out_dir, "replay.csv"), *flags]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("session_replay failed:\n" + r.stderr)


def train_svm(X, y):
    """Linear SVM -> (weights, bias) with score > 0 meaning 'closed'."""
    svm = cv2.ml.SVM_create()
    svm.setType(cv2.ml.SVM_C_SVC)
    svm.setKernel(cv2.ml.SVM_LINEAR)
    svm.setC(0.1)
    svm.setClassWeights(np.array([1.0, 20.0]))   # ~70 blinks vs ~5800 open frames
    svm.train(X, cv2.ml.ROW_SAMPLE, y)
    # OpenCV compresses a linear SVM to one support vector; its raw output is
    # alpha*sv.x - rho and is NEGATIVE for class 1, so negate it.
    rho, alpha, _ = svm.getDecisionFunction(0)
    w = -(alpha[0, 0] * svm.getSupportVectors()[0]).astype(np.float32)
    b = np.float32(rho)
    raw = svm.predict(X[:50], flags=cv2.ml.STAT_MODEL_RAW_OUTPUT)[1].ravel()
    assert np.allclose(X[:50] @ w + b, -raw, atol=1e-3), "weight extraction does not reproduce the SVM"
    return w, b


def write_model(path, w, b, threshold):
    np.concatenate([w, [b, threshold]]).astype("<f4").tofile(path)


def write_header(path, w, b, threshold, provenance):
    """The same float32 values as write_model, as C source for main.cpp.
    %.9g round-trips a float32 exactly, so device and replay use identical numbers."""
    def f(v):
        s = "%.9g" % np.float32(v)
        if not any(c in s for c in ".eE"):
            s += ".0"   # "0" -> "0.0f": a bare "0f" isn't a valid C++ float literal
        return s + "f"
    body = ",\n".join("    " + ", ".join(f(v) for v in w[i:i + 6]) for i in range(0, len(w), 6))
    with open(path, "w", newline="\n") as out:
        out.write(
            "// Generated by fatigue-helmet/python/train_blink_classifier.py -- do not edit by hand.\n"
            + "".join("// " + line + "\n" for line in provenance)
            + "// Rider- and mount-specific: retrain for a different rider or camera position.\n"
            "#pragma once\n#include \"EyeBlinkEAR.h\"\n\n"
            f"static const float BLINK_HOG_BIAS      = {f(b)};\n"
            f"static const float BLINK_HOG_THRESHOLD = {f(threshold)};\n"
            f"static const float BLINK_HOG_WEIGHTS[] = {{\n{body}\n}};\n"
            "static_assert(sizeof(BLINK_HOG_WEIGHTS) / sizeof(BLINK_HOG_WEIGHTS[0]) == EyeBlinkEAR::HOG_LEN,\n"
            "              \"weights do not match the firmware's HOG feature length\");\n")


def score_events(ev_idx, state, blinks):
    """ev_idx: frame indices where the device counted a blink."""
    closed = np.where(state == "closed")[0]
    tp = sum(any(abs(e - c) <= TOL for e in ev_idx for c in blk) for blk in blinks)
    fp = in_unsure = 0
    for e in ev_idx:
        if state[e] == "unsure":
            in_unsure += 1
        elif len(closed) == 0 or np.abs(closed - e).min() > TOL:
            fp += 1
    return tp, fp, in_unsure


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--session", required=True, help="session folder with frames/ and blink_labels.csv")
    ap.add_argument("--threshold", type=float, default=None,
                    help="score threshold for the final model (default: best F1 in cross-validation)")
    ap.add_argument("--header", default=os.path.join(HERE, "..", "firmware", "src", "BlinkWeights.h"),
                    help="where to write the firmware weights header (default: firmware/src/BlinkWeights.h)")
    ap.add_argument("--jitter-n", type=int, default=4,
                    help="extra training copies per labelled frame, HOG crop re-centred on a random "
                         "+-jitter-px offset from the locked ROI (0 disables). The classifier otherwise "
                         "only ever sees one exact framing, and a moving ROI (drift correction, a "
                         "re-tapped eye box) is never exactly that framing -- see session-116-blink-eval "
                         "memory: this took a held-out session from 12/28 to 19/28 blinks caught at "
                         "2.7 FA/min, vs. 4.6 FA/min without it. Default 4,16 is that tested setting.")
    ap.add_argument("--jitter-px", type=int, default=16, help="max +-offset in px for --jitter-n")
    args = ap.parse_args()
    s = args.session
    work = os.path.join(s, "blink_classifier")
    os.makedirs(work, exist_ok=True)

    rows = list(csv.DictReader(open(os.path.join(s, "blink_labels.csv"))))
    idx_of = {int(r["timestamp_ms"]): int(r["frame_idx"]) for r in rows}
    # Indexed by frame_idx (not row position): session_101's labels covered
    # every frame contiguously from 0, so row position happened to equal
    # frame_idx there. session_119's windowed labels don't, so state must be
    # addressable by the same frame_idx used everywhere below (fidx, closed,
    # score_events's ev_idx) or lookups land on the wrong frame or go OOB.
    state = np.full(max(int(r["frame_idx"]) for r in rows) + 1, "", dtype="<U10")
    for r in rows:
        state[int(r["frame_idx"])] = r["state"]

    dump = os.path.join(work, "hog_features.bin")
    jitter_flags = [f"--hog-jitter={args.jitter_n},{args.jitter_px}"] if args.jitter_n else []
    replay(s, work, "--hog-dump=" + dump, *jitter_flags)
    rec = np.fromfile(dump, dtype=[("ts", "<u4"), ("mean", "<f4"), ("f", "<f4", (HOG_LEN,))])
    # session_replay dumps every frame after the eye lock, but blink_labels.csv
    # may only cover representative windows rather than the whole session
    # (session_119: 5 windows, ~9% of frames) -- keep only the dumped rows
    # that actually have a hand label instead of assuming full contiguous
    # coverage the way session_101's blink_labels.csv had it.
    rec = rec[np.array([t in idx_of for t in rec["ts"]])]
    # --hog-jitter dumps 1+jitter_n records per frame, same timestamp each --
    # fidx (and everything derived from it below) just gets that many more
    # rows per label, all sharing one frame's ground truth.
    fidx = np.array([idx_of[t] for t in rec["ts"]])      # labelled frames only
    X, st = rec["f"], state[fidx]
    y = (st == "closed").astype(np.int32)

    closed = np.where(state == "closed")[0]
    closed = closed[closed >= fidx[0]]                    # blinks before the lock can't be seen
    blinks = np.split(closed, np.where(np.diff(closed) > 2)[0] + 1) if len(closed) else []
    near = np.array([len(closed) > 0 and np.abs(closed - i).min() <= TOL for i in fidx])
    usable = (st != "unsure") & ((st == "closed") | ~near)  # drop half-closed transition frames
    # NOTE: excluding "squint" the same as "unsure", and auto-tuning the SVM's class
    # weight from the actual pos/neg ratio, were both tried on session_119's full
    # (17,100-frame) hand-labelled session to fix a badly miscalibrated classifier
    # (non-monotonic recall/false-alarms across thresholds, ~2-4% precision). Neither
    # helped there, and both made the small, curated 7-window result WORSE (69%/69%
    # recall/precision fixed-weight-with-squint dropped to 44-52% precision with
    # these changes) -- so both are reverted here. The full-session classifier
    # appears to need a fundamentally different approach (nonlinear model, more
    # features, per-lighting calibration), not a hyperparameter tweak.
    print(f"{len(set(fidx))} frames after eye lock ({len(rec)} training rows with "
          f"{args.jitter_n}x{args.jitter_px}px jitter), {len(blinks)} labelled blinks, "
          f"{(st == 'unsure').sum()} unsure rows excluded")

    thresholds = [0.0, 0.25, 0.5, 0.75]
    tally = {t: [0, 0, 0] for t in thresholds}
    for fold_i, te in enumerate(np.array_split(np.arange(len(rec)), FOLDS)):
        lo, hi = fidx[te[0]], fidx[te[-1]]
        tr = np.where(usable & ((fidx < lo - 5) | (fidx > hi + 5)))[0]
        n_pos = int(y[tr].sum())
        w, b = train_svm(X[tr], y[tr])
        fold_blinks = [blk for blk in blinks if lo <= blk[0] <= hi]
        print(f"  fold {fold_i}: frame_idx [{lo},{hi}], {len(tr)} train rows "
              f"({n_pos} closed), {len(fold_blinks)} held-out blinks")
        for t in thresholds:
            model = os.path.join(work, "fold_model.bin")
            write_model(model, w, b, t)
            out = os.path.join(work, "fold_hog.csv")
            replay(s, work, "--hog-model=" + model, "--hog-csv=" + out)
            # This replays the WHOLE session, so most detected events fall
            # outside our labelled windows and have no ground truth -- only
            # score events landing on a labelled frame (see the same
            # windowed-labels note above idx_of's first use).
            ev = [idx_of[int(r["timestamp_ms"])] for r in csv.DictReader(open(out))
                  if r["blink"] == "1" and int(r["timestamp_ms"]) in idx_of]
            ev = [e for e in ev if lo <= e <= hi]
            tp, fp, un = score_events(ev, state, fold_blinks)
            print(f"    threshold {t:+.2f}: {tp}/{len(fold_blinks)} caught, {fp} false alarms")
            for k, v in enumerate((tp, fp, un)):
                tally[t][k] += v

    print("\nCross-validated through session_replay (firmware scoring + blink counting):")
    best, best_f1 = thresholds[0], -1
    for t in thresholds:
        tp, fp, un = tally[t]
        rec_, prec = tp / max(len(blinks), 1), tp / max(tp + fp, 1)
        f1 = 2 * rec_ * prec / max(rec_ + prec, 1e-9)
        if f1 > best_f1:
            best, best_f1 = t, f1
        print(f"  threshold {t:+.2f}: caught {tp}/{len(blinks)} ({rec_:.0%}), "
              f"false alarms {fp}, precision {prec:.0%}, events inside unsure footage {un}")

    th = best if args.threshold is None else args.threshold
    w, b = train_svm(X[usable], y[usable])
    model = os.path.join(s, "blink_model.bin")
    write_model(model, w, b, th)
    tp, fp, _ = tally[th] if th in tally else (0, 0, 0)
    jitter_note = f", +-{args.jitter_px}px x{args.jitter_n} ROI jitter" if args.jitter_n else ""
    provenance = [f"Trained on {os.path.basename(os.path.normpath(s))}: {len(blinks)} labelled blinks, "
                  f"{len(set(fidx))} frames after eye lock{jitter_note}."]
    if th in tally:
        provenance.append(f"Cross-validated at threshold {th:+.2f}: caught {tp}/{len(blinks)}, "
                          f"{fp} false alarms (precision {tp / max(tp + fp, 1):.0%}).")
    write_header(args.header, w, b, th, provenance)
    print(f"\nFinal model (all labelled frames, threshold {th:+.2f}) -> {model}\n"
          f"Firmware weights -> {args.header}")


if __name__ == "__main__":
    main()
