#!/usr/bin/env python3
"""
train_blink_classifier.py — Train the firmware's HOG blink classifier from hand labels.
=======================================================================================
The firmware's HogBlinkDetector (src/EyeBlinkEAR.h) scores each frame as
weights . hog(crop) + bias and counts a blink when the score crosses a
threshold. This script finds those weights.

Everything that touches pixels runs through tools/session_replay, which
compiles the same EyeBlinkEAR.h the ESP32 does:
  1. session_replay --hog-dump   -> HOG features exactly as the device computes them
  2. train a linear SVM on those features against blink_labels.csv
  3. cross-validate END TO END: for each of 5 contiguous time blocks, train on
     the other blocks, write a model, and let session_replay (i.e. the
     firmware's scoring + blink-counting logic) find blinks in the held-out block
  4. train on everything and write <session>/blink_model.bin for session_replay
     and the same numbers as firmware/src/BlinkWeights.h for main.cpp

blink_labels.csv: timestamp_ms,frame_idx,state with state in
open / closed / squint / unsure. "unsure" frames (exposure dropouts, hand over
the camera, half-closures) are left out of training and of the scores.

Usage:
    python train_blink_classifier.py --session ../../sessions/session_101
"""

import argparse
import csv
import os
import subprocess
import sys

import cv2
import numpy as np

HOG_LEN = 756
HERE = os.path.dirname(os.path.abspath(__file__))
REPLAY = os.path.join(HERE, "..", "firmware", "tools", "session_replay", "session_replay.exe")
TOL = 2          # an event within 2 frames of a labelled closed frame is that blink
FOLDS = 5


def replay(session, out_dir, *flags):
    cmd = [REPLAY, os.path.join(session, "frames"), os.path.join(out_dir, "replay.csv"), *flags]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("session_replay failed:\n" + r.stderr)


def train_svm(X, y):
    """Linear SVM -> (weights, bias) with score > 0 meaning 'closed'."""
    svm = cv2.ml.SVM_create()
    svm.setType(cv2.ml.SVM_C_SVC)
    svm.setKernel(cv2.ml.SVM_LINEAR)
    svm.setC(0.1)
    svm.setClassWeights(np.array([1.0, 20.0]))   # ~70 blinks vs ~5800 open frames
    svm.train(X, cv2.ml.ROW_SAMPLE, y)
    # OpenCV compresses a linear SVM to one support vector; its raw output is
    # alpha*sv.x - rho and is NEGATIVE for class 1, so negate it.
    rho, alpha, _ = svm.getDecisionFunction(0)
    w = -(alpha[0, 0] * svm.getSupportVectors()[0]).astype(np.float32)
    b = np.float32(rho)
    raw = svm.predict(X[:50], flags=cv2.ml.STAT_MODEL_RAW_OUTPUT)[1].ravel()
    assert np.allclose(X[:50] @ w + b, -raw, atol=1e-3), "weight extraction does not reproduce the SVM"
    return w, b


def write_model(path, w, b, threshold):
    np.concatenate([w, [b, threshold]]).astype("<f4").tofile(path)


def write_header(path, w, b, threshold, provenance):
    """The same float32 values as write_model, as C source for main.cpp.
    %.9g round-trips a float32 exactly, so device and replay use identical numbers."""
    f = lambda v: "%.9gf" % np.float32(v)
    body = ",\n".join("    " + ", ".join(f(v) for v in w[i:i + 6]) for i in range(0, len(w), 6))
    with open(path, "w", newline="\n") as out:
        out.write(
            "// Generated by fatigue-helmet/python/train_blink_classifier.py -- do not edit by hand.\n"
            + "".join("// " + line + "\n" for line in provenance)
            + "// Rider- and mount-specific: retrain for a different rider or camera position.\n"
            "#pragma once\n#include \"EyeBlinkEAR.h\"\n\n"
            f"static const float BLINK_HOG_BIAS      = {f(b)};\n"
            f"static const float BLINK_HOG_THRESHOLD = {f(threshold)};\n"
            f"static const float BLINK_HOG_WEIGHTS[] = {{\n{body}\n}};\n"
            "static_assert(sizeof(BLINK_HOG_WEIGHTS) / sizeof(BLINK_HOG_WEIGHTS[0]) == EyeBlinkEAR::HOG_LEN,\n"
            "              \"weights do not match the firmware's HOG feature length\");\n")


def score_events(ev_idx, state, blinks):
    """ev_idx: frame indices where the device counted a blink."""
    closed = np.where(state == "closed")[0]
    tp = sum(any(abs(e - c) <= TOL for e in ev_idx for c in blk) for blk in blinks)
    fp = in_unsure = 0
    for e in ev_idx:
        if state[e] == "unsure":
            in_unsure += 1
        elif len(closed) == 0 or np.abs(closed - e).min() > TOL:
            fp += 1
    return tp, fp, in_unsure


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--session", required=True, help="session folder with frames/ and blink_labels.csv")
    ap.add_argument("--threshold", type=float, default=None,
                    help="score threshold for the final model (default: best F1 in cross-validation)")
    ap.add_argument("--header", default=os.path.join(HERE, "..", "firmware", "src", "BlinkWeights.h"),
                    help="where to write the firmware weights header (default: firmware/src/BlinkWeights.h)")
    args = ap.parse_args()
    s = args.session
    work = os.path.join(s, "blink_classifier")
    os.makedirs(work, exist_ok=True)

    rows = list(csv.DictReader(open(os.path.join(s, "blink_labels.csv"))))
    idx_of = {int(r["timestamp_ms"]): int(r["frame_idx"]) for r in rows}
    state = np.array([r["state"] for r in rows])

    dump = os.path.join(work, "hog_features.bin")
    replay(s, work, "--hog-dump=" + dump)
    rec = np.fromfile(dump, dtype=[("ts", "<u4"), ("mean", "<f4"), ("f", "<f4", (HOG_LEN,))])
    fidx = np.array([idx_of[t] for t in rec["ts"]])      # frames after the eye lock
    X, st = rec["f"], state[fidx]
    y = (st == "closed").astype(np.int32)

    closed = np.where(state == "closed")[0]
    closed = closed[closed >= fidx[0]]                    # blinks before the lock can't be seen
    blinks = np.split(closed, np.where(np.diff(closed) > 2)[0] + 1) if len(closed) else []
    near = np.array([len(closed) > 0 and np.abs(closed - i).min() <= TOL for i in fidx])
    usable = (st != "unsure") & ((st == "closed") | ~near)  # drop half-closed transition frames
    print(f"{len(rec)} frames after eye lock, {len(blinks)} labelled blinks, "
          f"{(st == 'unsure').sum()} unsure frames excluded")

    thresholds = [0.0, 0.25, 0.5, 0.75]
    tally = {t: [0, 0, 0] for t in thresholds}
    for te in np.array_split(np.arange(len(rec)), FOLDS):
        lo, hi = fidx[te[0]], fidx[te[-1]]
        tr = np.where(usable & ((fidx < lo - 5) | (fidx > hi + 5)))[0]
        w, b = train_svm(X[tr], y[tr])
        fold_blinks = [blk for blk in blinks if lo <= blk[0] <= hi]
        for t in thresholds:
            model = os.path.join(work, "fold_model.bin")
            write_model(model, w, b, t)
            out = os.path.join(work, "fold_hog.csv")
            replay(s, work, "--hog-model=" + model, "--hog-csv=" + out)
            ev = [idx_of[int(r["timestamp_ms"])] for r in csv.DictReader(open(out)) if r["blink"] == "1"]
            ev = [e for e in ev if lo <= e <= hi]
            for k, v in enumerate(score_events(ev, state, fold_blinks)):
                tally[t][k] += v

    print("\nCross-validated through session_replay (firmware scoring + blink counting):")
    best, best_f1 = thresholds[0], -1
    for t in thresholds:
        tp, fp, un = tally[t]
        rec_, prec = tp / max(len(blinks), 1), tp / max(tp + fp, 1)
        f1 = 2 * rec_ * prec / max(rec_ + prec, 1e-9)
        if f1 > best_f1:
            best, best_f1 = t, f1
        print(f"  threshold {t:+.2f}: caught {tp}/{len(blinks)} ({rec_:.0%}), "
              f"false alarms {fp}, precision {prec:.0%}, events inside unsure footage {un}")

    th = best if args.threshold is None else args.threshold
    w, b = train_svm(X[usable], y[usable])
    model = os.path.join(s, "blink_model.bin")
    write_model(model, w, b, th)
    tp, fp, _ = tally[th] if th in tally else (0, 0, 0)
    provenance = [f"Trained on {os.path.basename(os.path.normpath(s))}: {len(blinks)} labelled blinks, "
                  f"{len(rec)} frames after eye lock."]
    if th in tally:
        provenance.append(f"Cross-validated at threshold {th:+.2f}: caught {tp}/{len(blinks)}, "
                          f"{fp} false alarms (precision {tp / max(tp + fp, 1):.0%}).")
    write_header(args.header, w, b, th, provenance)
    print(f"\nFinal model (all labelled frames, threshold {th:+.2f}) -> {model}\n"
          f"Firmware weights -> {args.header}")


if __name__ == "__main__":
    main()
